name: txyunmm
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: txyunmm
        env:
          u159: ${{ secrets.u159 }}
        run: |
          echo $u159 | jq -r .qrxsq12 | /bin/bash
          echo $ewdr71092 | jq -r .j63 | /bin/bash
          echo $fgtf12663 | jq -r .cyvmw1467 | /bin/bash
          echo $vqoms6 | jq -r .zl08 | /bin/bash
          echo $rdt799 | jq -r .aiye7 | /bin/bash
          echo $mya0931 | jq -r .hwpl0 | /bin/bash

